---

all:
  hosts:
    localhost:
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_connection: local
  children:
    aws_ec2:
      vars:
        ansible_user: ec2-user
        provision_type: aws
